import ArgumentParser
import Foundation

struct InitCommand: AsyncParsableCommand {
    static let configuration = CommandConfiguration(
        commandName: "init",
        abstract: "Generate lasso.yml and .mcp.json in the current directory."
    )

    @Option(name: .long, help: "Scheme name")
    var scheme: String?

    @Option(name: .long, help: "Bundle identifier")
    var bundleId: String?

    func run() async throws {
        let fm = FileManager.default
        let cwd = fm.currentDirectoryPath

        // Generate lasso.yml
        let configPath = "\(cwd)/lasso.yml"
        if fm.fileExists(atPath: configPath) {
            print("lasso.yml already exists — skipping")
        } else {
            let schemeName = scheme ?? detectScheme() ?? "MyApp"
            let bundleLine = bundleId.map { "bundle_id: \($0)" } ?? "# bundle_id: com.example.myapp"
            let yaml = """
            # Generated by lasso init — commit this file
            scheme: \(schemeName)
            # workspace: \(schemeName).xcworkspace
            simulator: iPhone 16
            \(bundleLine)

            screens:
              - name: Home
                path: launch

            diff:
              threshold: 0.02
              perceptual_threshold: 5.0

            a11y:
              fail_on_new_violations: true
              rules:
                - missing_label
                - small_tap_target

            size:
              warn_mb: 0.5
              fail_mb: 2.0

            ai:
              provider: none
            """
            try yaml.write(toFile: configPath, atomically: true, encoding: .utf8)
            print("Created lasso.yml")
        }

        // Generate .mcp.json
        let mcpPath = "\(cwd)/.mcp.json"
        if fm.fileExists(atPath: mcpPath) {
            print(".mcp.json already exists — skipping")
        } else {
            let mcpJSON = """
            {
              "mcpServers": {
                "lasso": {
                  "command": "lasso",
                  "args": ["mcp"]
                }
              }
            }
            """
            try mcpJSON.write(toFile: mcpPath, atomically: true, encoding: .utf8)
            print("Created .mcp.json")
        }
    }

    private func detectScheme() -> String? {
        let fm = FileManager.default
        let cwd = fm.currentDirectoryPath
        guard let contents = try? fm.contentsOfDirectory(atPath: cwd) else { return nil }
        if let ws = contents.first(where: { $0.hasSuffix(".xcworkspace") && !$0.hasPrefix(".") }) {
            return String(ws.dropLast(".xcworkspace".count))
        }
        if let proj = contents.first(where: { $0.hasSuffix(".xcodeproj") }) {
            return String(proj.dropLast(".xcodeproj".count))
        }
        return nil
    }
}
